#!/usr/bin/env bash
# Shared helpers for the ordered platform bootstrap scripts (00 -> 30).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ARGO_NS="${ARGO_NS:-openshift-gitops}"
AWS_IDENTITY_SECRET="${AWS_IDENTITY_SECRET:-aws-static-credentials}"
AWS_PUBLISHER_IDENTITY_SECRET="${AWS_PUBLISHER_IDENTITY_SECRET:-aws-static-credentials-publisher}"

die(){ echo "ERROR: $*" >&2; exit 1; }
say(){ echo ">> $*"; }

resolve_env(){
  ENV="${1:?usage: $(basename "$0") <env>   (e.g. doc4)}"
  COMMON="$ROOT/gitops/envs/$ENV/common.yaml"
  VALUES="$ROOT/gitops/envs/$ENV/values.yaml"
  [[ -f "$COMMON" && -f "$VALUES" ]] || die "env files gitops/envs/$ENV/{common,values}.yaml not found"
}

require_cluster(){
  command -v oc >/dev/null 2>&1 || die "oc not found in PATH"
  command -v helm >/dev/null 2>&1 || die "helm not found in PATH"
  oc whoami >/dev/null 2>&1 || die "not logged in to OpenShift (oc login ...)"
  oc get argocd "$ARGO_NS" -n "$ARGO_NS" >/dev/null 2>&1 || die "OpenShift GitOps ArgoCD '$ARGO_NS' not found - run ./bootstrap/00-prereqs.sh $ENV first"
}

cfg(){ grep -E "^$2:" "$1" 2>/dev/null | head -1 | sed -E 's/^[^:]*: *//; s/[ "].*//'; }
env_account(){
  local value
  value="$(grep -oE 'account: *\{ *id: *[A-Za-z0-9._-]+' "$COMMON" | head -1 | sed -E 's/.*id: *//')"
  echo "${value:-mas}"
}
env_cluster(){ cfg "$COMMON" clusterId; }
env_instance(){ cfg "$VALUES" instanceId; }
env_mongo_ns(){ grep -oE 'namespace: *[A-Za-z0-9._-]+' "$VALUES" | head -1 | sed -E 's/.*: *//'; }
aws_cluster_path(){ echo "mas/$(env_account)/$(env_cluster)"; }
aws_instance_path(){ echo "$(aws_cluster_path)/$(env_instance)"; }

env_feature_enabled(){
  local key="$1" value
  value="$(awk -v key="$key" '/^enable:[[:space:]]*$/ { inside=1; next } inside && /^[^[:space:]]/ { exit } inside && $1 == key ":" { print tolower($2); exit }' "$VALUES")"
  if [[ -z "$value" ]]; then
    value="$(awk -v key="$key" '/^enable:[[:space:]]*$/ { inside=1; next } inside && /^[^[:space:]]/ { exit } inside && $1 == key ":" { print tolower($2); exit }' "$ROOT/gitops/values.yaml")"
  fi
  [[ "$value" == "true" ]]
}

render_component(){
  local component="$1"; shift
  helm template platform "$ROOT/gitops" -f "$COMMON" -f "$VALUES" --set component="$component" "$@"
}

apply_component(){
  local component="$1"; shift
  say "rendering and applying component '$component' to $ARGO_NS"
  render_component "$component" "$@" | oc apply -f -
}

validate_static_credentials(){
  local secret_name="${1:?secret name required}" purpose="${2:?identity purpose required}" key value
  oc get secret "$secret_name" -n "$ARGO_NS" >/dev/null 2>&1 || die "Secret $ARGO_NS/$secret_name is missing for $purpose (see INSTALL.md)"
  for key in region aws_access_key_id aws_secret_access_key; do
    value="$(oc get secret "$secret_name" -n "$ARGO_NS" -o "jsonpath={.data.$key}" 2>/dev/null || true)"
    [[ -n "$value" ]] || die "Secret $ARGO_NS/$secret_name is missing '$key'"
  done
}

validate_aws_identity_inputs(){
  validate_static_credentials "$AWS_IDENTITY_SECRET" "read-only manifest generation"
  validate_static_credentials "$AWS_PUBLISHER_IDENTITY_SECRET" "generated SLS/DRO publishing"
}

verify_avp_repo_server(){
  local type region
  type="$(oc exec -n "$ARGO_NS" deployment/openshift-gitops-repo-server -c avp-helm -- printenv AVP_TYPE 2>/dev/null | tr -d '\r' || true)"
  region="$(oc exec -n "$ARGO_NS" deployment/openshift-gitops-repo-server -c avp-helm -- printenv AWS_REGION 2>/dev/null | tr -d '\r' || true)"
  [[ "$type" == "awssecretsmanager" && -n "$region" ]] || die "AWS Secrets Manager CMP is unavailable - run ./bootstrap/00-prereqs.sh $ENV"
}

verify_aws_secrets(){
  local set_name="${1:?verify_aws_secrets requires mongo, mas, or generated}"
  local ipath cpath manifest
  ipath="$(aws_instance_path)"
  cpath="$(aws_cluster_path)"
  case "$set_name" in
    mongo)
      manifest="apiVersion: v1
kind: Secret
metadata:
  name: aws-preflight-mongo
stringData:
  mongoPassword: <path:$ipath/mongo#password>
  slsMongoUsername: <path:$ipath/sls-mongo#username>
  slsMongoPassword: <path:$ipath/sls-mongo#password>"
      # Note: the Mongo CA is generated by cert-manager in-cluster and its public cert is
      # published to mongo#ca.crt after the mongo instance syncs; it is not seeded here.
      ;;
    mas)
      manifest="apiVersion: v1
kind: Secret
metadata:
  name: aws-preflight-mas
stringData:
  entitlement: <path:$cpath/entitlement#image_pull_secret_b64>
  license: <path:$ipath/license#license_file>
  jdbcUsername: <path:$ipath/jdbc-system#username>
  jdbcPassword: <path:$ipath/jdbc-system#password>
  jdbcUrl: <path:$ipath/jdbc-system#jdbc_url>
  mongoUsername: <path:$ipath/mongo#username>
  mongoPassword: <path:$ipath/mongo#password>
  mongoHost: <path:$ipath/mongo#host>
  mongoCa: <path:$ipath/mongo#ca.crt>
  publicTlsCert: <path:$ipath/certs/public#tls_crt_b64>
  publicTlsKey: <path:$ipath/certs/public#tls_key_b64>
  publicCaCert: <path:$ipath/certs/public#ca_crt_b64>"
      ;;
    generated)
      manifest="apiVersion: v1
kind: Secret
metadata:
  name: aws-preflight-generated
stringData:
  slsUrl: <path:$ipath/sls#url>
  slsRegistrationKey: <path:$ipath/sls#registration_key>
  slsCa: <path:$ipath/sls#ca.crt>
  droUrl: <path:$cpath/dro#url>
  droApiToken: <path:$cpath/dro#api_token>
  droCa: <path:$cpath/dro#ca.crt>"
      ;;
    *) die "unknown AWS secret set '$set_name'" ;;
  esac
  printf '%s\n' "$manifest" | oc exec -i -n "$ARGO_NS" deployment/openshift-gitops-repo-server -c avp-helm -- argocd-vault-plugin generate - >/dev/null || die "AWS Secrets Manager preflight failed for '$set_name' under $ipath"
}
