apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: {{ include "grafana.ns" . }}
  labels: { dashboards: grafana }
spec:
  config:
    auth: { disable_login_form: "false" }
    log: { mode: console }
  version: {{ .Values.grafanaVersion | quote }}
  route:
    metadata: {}
    spec: { tls: { termination: edge } }
