apiVersion: v1
kind: Secret
metadata:
  name: repo-platform
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: CHANGE_ME_PLATFORM_REPO_URL
  username: CHANGE_ME_GITLAB_DEPLOY_TOKEN_USERNAME
  password: CHANGE_ME_GITLAB_DEPLOY_TOKEN_VALUE
