# instance-scope
instanceId: CHANGE_ME
mongo: { namespace: mongo-CHANGE_ME, members: 3, version: "7.0.23" }
jdbc:  { sslEnabled: false }
dro:   { namespace: ibm-software-central }
sls:   { syncEnabled: true }
