namespace: openshift-gitops
accountId: ""
clusterId: ""
instanceId: ""
droNamespace: ibm-software-central
slsNamespace: ""
pollSeconds: 300
authConfigMap: aws-secrets-manager-publisher-auth
identitySecret: oneidentity-a2a-publisher
image: "quay.io/ibmmas/cli@sha256:887cc3059a04601241687711df0c03d662931e6719121eec0eb0490001b2c8b9"
resources:
  requests: { cpu: 10m, memory: 64Mi }
  limits: { cpu: 200m, memory: 512Mi }
