apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Values.namespace }}
  labels: { app.kubernetes.io/part-of: mas-platform, app.kubernetes.io/name: vault-unseal }
