{{- if .Values.core.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: mas-{{ .Values.instanceId }}-core
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.instanceId }}-cert-public
  namespace: mas-{{ .Values.instanceId }}-core
data:
  tls.crt: <path:{{ .Values.certPath }}#tls_crt_b64>
  tls.key: <path:{{ .Values.certPath }}#tls_key_b64>
  ca.crt: <path:{{ .Values.certPath }}#ca_crt_b64>
{{- end }}
