apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: openshift-gitops
type: Opaque
stringData:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: k8s
  AVP_K8S_ROLE: mas-gitops
  VAULT_ADDR: http://vault-active.vault.svc.cluster.local:8200
