# Admin and SLS-Mongo passwords are resolved from AWS Secrets Manager.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.resource }}-admin-password"
  namespace: "{{ .Values.namespace }}"
stringData:
  password: "{{ .Values.adminPasswordPath }}"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Values.resource }}-slsmongo-password"
  namespace: "{{ .Values.namespace }}"
stringData:
  password: "{{ .Values.slsmongoPasswordPath }}"
