#!/usr/bin/env bash
set -euo pipefail
# Back up the OPERATOR-GENERATED Manage secrets into Vault so a reinstall / DR rebuild can REUSE
# them instead of generating new ones:
#   - ${WORKSPACE_ID}-manage-encryptionsecret  (MXE_SECURITY_CRYPTO_KEY / CRYPTOX_KEY)
#         -> secret/<IP>/manage-crypto#cryptoKey,cryptoxKey
#   - ${INSTANCE_ID}-credentials-superuser     (username / password — the MAS admin login)
#         -> secret/<IP>/superuser#username,password
#
# WHY: with MANAGE_AUTO_GENERATE_ENCRYPTION_KEYS=true, MAS mints the crypto keys itself and they
# exist ONLY in the in-cluster secret; a reinstall would mint DIFFERENT keys and fail to decrypt the
# existing DB. The admin superuser is likewise generated by the operator. Capturing both into Vault
# makes them reproducible (set MANAGE_AUTO_GENERATE_ENCRYPTION_KEYS=false + ALLOW_CUSTOM_MANAGE_CRYPTO_KEYS=true
# on the next install to reuse the crypto keys). Idempotent: re-running just refreshes Vault with the
# current live values. Run AFTER Manage is deployed (the encryption secret only exists by then).
#
#   export VAULT_TOKEN=...; ./scripts/backup-manage-secrets.sh <path/to/cluster.env>
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
source "$ROOT/scripts/lib-argocd-oc.sh"

ENVFILE="${1:?usage: backup-manage-secrets.sh <path/to/cluster.env>}"
# shellcheck disable=SC1090
set -a; . "$ENVFILE"; set +a
: "${ACCOUNT_ID:?}"; : "${CLUSTER_ID:?}"; : "${INSTANCE_ID:?}"; : "${WORKSPACE_ID:?}"
KV="${KV_MOUNT:-secret}"; VAULT_NS="${VAULT_NS:-vault}"; VAULT_POD="${VAULT_POD:-vault-0}"; VADDR="${VADDR:-http://127.0.0.1:8200}"
CORE_NS="mas-${INSTANCE_ID}-core"; MANAGE_NS="mas-${INSTANCE_ID}-manage"
[[ -z "${VAULT_TOKEN:-}" ]] && { echo "ERROR: export VAULT_TOKEN first" >&2; exit 1; }
IP="$ACCOUNT_ID/$CLUSTER_ID/$INSTANCE_ID"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT

# read a single base64 data key from a secret -> stdout (decoded); empty if missing
secret_key() { oc get secret "$2" -n "$1" -o jsonpath="{.data.${3//./\\.}}" 2>/dev/null | base64 -d 2>/dev/null || true; }

backed_up=0

# --- Manage crypto keys (from the workspace encryption secret, in the manage namespace) ---
ENC_SECRET="${WORKSPACE_ID}-manage-encryptionsecret"
crypto="$(secret_key  "$MANAGE_NS" "$ENC_SECRET" MXE_SECURITY_CRYPTO_KEY)"
cryptox="$(secret_key "$MANAGE_NS" "$ENC_SECRET" MXE_SECURITY_CRYPTOX_KEY)"
if [[ -n "$crypto" && -n "$cryptox" ]]; then
  printf '%s' "$crypto"  > "$TMP/cryptoKey"
  printf '%s' "$cryptox" > "$TMP/cryptoxKey"
  oc cp "$TMP/cryptoKey"  "$VAULT_NS/$VAULT_POD:/tmp/cryptoKey"
  oc cp "$TMP/cryptoxKey" "$VAULT_NS/$VAULT_POD:/tmp/cryptoxKey"
  oc exec -n "$VAULT_NS" "$VAULT_POD" -- sh -c \
    "export VAULT_ADDR=$VADDR VAULT_TOKEN='$VAULT_TOKEN'; \
     vault kv put $KV/$IP/manage-crypto cryptoKey=@/tmp/cryptoKey cryptoxKey=@/tmp/cryptoxKey >/dev/null; \
     rm -f /tmp/cryptoKey /tmp/cryptoxKey"
  echo ">> backed up Manage crypto keys -> $KV/$IP/manage-crypto (cryptoKey=${#crypto} bytes, cryptoxKey=${#cryptox} bytes)"
  backed_up=1
else
  echo ">> WARN: $MANAGE_NS/$ENC_SECRET not found or empty — skipping crypto backup (is Manage deployed yet?)" >&2
fi

# --- MAS admin superuser (operator-generated, in the core namespace) ---
SU_SECRET="${INSTANCE_ID}-credentials-superuser"
su_user="$(secret_key "$CORE_NS" "$SU_SECRET" username)"
su_pass="$(secret_key "$CORE_NS" "$SU_SECRET" password)"
if [[ -n "$su_user" && -n "$su_pass" ]]; then
  printf '%s' "$su_user" > "$TMP/username"
  printf '%s' "$su_pass" > "$TMP/password"
  oc cp "$TMP/username" "$VAULT_NS/$VAULT_POD:/tmp/su_username"
  oc cp "$TMP/password" "$VAULT_NS/$VAULT_POD:/tmp/su_password"
  oc exec -n "$VAULT_NS" "$VAULT_POD" -- sh -c \
    "export VAULT_ADDR=$VADDR VAULT_TOKEN='$VAULT_TOKEN'; \
     vault kv put $KV/$IP/superuser username=@/tmp/su_username password=@/tmp/su_password >/dev/null; \
     rm -f /tmp/su_username /tmp/su_password"
  echo ">> backed up MAS admin superuser -> $KV/$IP/superuser (username=$su_user)"
  backed_up=1
else
  echo ">> WARN: $CORE_NS/$SU_SECRET not found or empty — skipping superuser backup (is the Suite deployed yet?)" >&2
fi

[[ "$backed_up" == 1 ]] || { echo "ERROR: nothing backed up — neither secret was found. Run after Manage is deployed." >&2; exit 1; }
echo ">> Manage secret backup complete. To REUSE on a future install: set MANAGE_AUTO_GENERATE_ENCRYPTION_KEYS=false"
echo ">> and ALLOW_CUSTOM_MANAGE_CRYPTO_KEYS=true so load-secrets feeds these Vault crypto keys back to Manage."
