#!/usr/bin/env bash
set -euo pipefail
# ---------------------------------------------------------------------------
# Vault secret loader v3 — env-file driven, NON-SSL JDBC, DEDICATED Mongo.
#   ./load-secrets.sh <cluster.env>     (export VAULT_TOKEN + the REQUIRE vars first)
#
#   REQUIRE  : IBM_ENTITLEMENT_KEY  MAS_LICENSE_FILE  JDBC_USERNAME/PASSWORD/URL
#   OPTIONAL : JDBC_CA_CRT  (TCPS only; omit for non-SSL Oracle)
#   GENERATE : superuser, manage-crypto, mongo(admin) + sls-mongo passwords  (made once, reused)
#              Manage crypto keys are auto-generated by default. Existing Vault
#              values are reused; set ROTATE_MANAGE_CRYPTO_KEYS=true only for a
#              deliberate pre-production rotation before Manage owns data.
#   PINNED CA: the Mongo CA is generated ONCE here and stored in Vault ($IP/mongo-ca). cert-manager's
#              ca-issuer SIGNS the Mongo server cert with it, and mongocfg/sls/Manage TRUST the same CA
#              (mongo#ca.crt = sls-mongo#ca.crt = this CA). Because the CA is fixed in Vault (never
#              regenerated by cert-manager per deploy), it cannot rotate -> mongocfg can NEVER go
#              InvalidConfiguration from a CA mismatch. mongo#host points at the dedicated Mongo service.
# ---------------------------------------------------------------------------
ENVFILE="${1:?usage: load-secrets.sh <cluster.env>}"
# shellcheck disable=SC1090
set -a; . "$ENVFILE"; set +a
: "${ACCOUNT_ID:?}"; : "${CLUSTER_ID:?}"; : "${INSTANCE_ID:?}"
PREFIX="secret/${ACCOUNT_ID}/${CLUSTER_ID}"; IPREFIX="${PREFIX}/${INSTANCE_ID}"
KV="${KV_MOUNT:-secret}"
VAULT_NS="${VAULT_NS:-vault}"; VAULT_POD="${VAULT_POD:-vault-0}"; VADDR="${VADDR:-http://127.0.0.1:8200}"
# Dedicated Mongo for THIS instance (created by GitOps; not the shared mas-mongo-ce):
: "${MONGO_NS:?MONGO_NS must be set in the env file (e.g. MONGO_NS=mongo-drgitops) and MUST equal gitops/envs/<cluster>/values.yaml mongo.namespace}"
MONGO_HOST="${MONGO_HOST:-${INSTANCE_ID}-mongo-svc.${MONGO_NS}.svc.cluster.local}"
[[ -z "${VAULT_TOKEN:-}" ]] && { echo "ERROR: export VAULT_TOKEN first" >&2; exit 1; }
vrun(){ oc exec -n "$VAULT_NS" "$VAULT_POD" -- sh -c "export VAULT_ADDR=$VADDR VAULT_TOKEN='$VAULT_TOKEN'; $*"; }
vget(){ vrun "vault kv get -field='$2' $1" 2>/dev/null || true; }
b64(){ base64 | tr -d '\r\n'; }
gen(){
  local len="${1:-24}" out=""
  while (( ${#out} < len )); do
    out="${out}$(openssl rand -base64 "$len" | tr -dc 'A-Za-z0-9')"
  done
  printf '%s' "${out:0:len}"
}
putfile(){ oc cp "$1" "$VAULT_NS/$VAULT_POD:/tmp/$2"; }
truthy(){ [[ "${1:-}" =~ ^([Tt][Rr][Uu][Ee]|[Yy][Ee][Ss]|1)$ ]]; }

: "${IBM_ENTITLEMENT_KEY:?REQUIRED}"; : "${MAS_LICENSE_FILE:?REQUIRED path to license.dat}"
: "${JDBC_USERNAME:?REQUIRED}"; : "${JDBC_PASSWORD:?REQUIRED}"; : "${JDBC_URL:?REQUIRED}"
: "${MAS_LICENSE_ID:=}"; : "${JDBC_CA_CRT:=}"   # JDBC_CA_CRT empty => non-SSL

# generate-once (reused on re-run)
# NOTE: the MAS admin "superuser" is NOT generated here. MAS creates it itself as the operator-owned
# secret ${INSTANCE_ID}-credentials-superuser. We BACK IT UP into Vault (secret/<IP>/superuser) AFTER
# install via scripts/backup-manage-secrets.sh — alongside the auto-generated Manage crypto keys.
if truthy "${ALLOW_CUSTOM_MANAGE_CRYPTO_KEYS:-false}"; then
  MANAGE_CRYPTO_KEY="${MANAGE_CRYPTO_KEY:-$(vget "$IPREFIX/manage-crypto" cryptoKey)}"
  MANAGE_CRYPTOX_KEY="${MANAGE_CRYPTOX_KEY:-$(vget "$IPREFIX/manage-crypto" cryptoxKey)}"
elif truthy "${ROTATE_MANAGE_CRYPTO_KEYS:-false}"; then
  MANAGE_CRYPTO_KEY="$(gen 24)"
  MANAGE_CRYPTOX_KEY="$(gen 24)"
else
  MANAGE_CRYPTO_KEY="$(vget "$IPREFIX/manage-crypto" cryptoKey)"
  MANAGE_CRYPTOX_KEY="$(vget "$IPREFIX/manage-crypto" cryptoxKey)"
fi
MANAGE_CRYPTO_KEY="${MANAGE_CRYPTO_KEY:-$(gen 24)}"
MANAGE_CRYPTOX_KEY="${MANAGE_CRYPTOX_KEY:-$(gen 24)}"
MONGO_USERNAME="${MONGO_USERNAME:-admin}"
MONGO_PASSWORD="${MONGO_PASSWORD:-$(vget "$IPREFIX/mongo" password)}"; MONGO_PASSWORD="${MONGO_PASSWORD:-$(gen 24)}"
SLS_MONGO_USERNAME="${SLS_MONGO_USERNAME:-slsmongo}"
SLS_MONGO_PASSWORD="${SLS_MONGO_PASSWORD:-$(vget "$IPREFIX/sls-mongo" password)}"; SLS_MONGO_PASSWORD="${SLS_MONGO_PASSWORD:-$(gen 24)}"

# PINNED Mongo CA — generate ONCE (10y), reuse from Vault. This is the fix that makes mongocfg never
# fail: the CA is fixed in Vault, so cert-manager signs the server cert with it AND mongocfg trusts it,
# and it never rotates. Stored base64 (the form the rendered kubernetes.io/tls secret needs).
MONGO_CA_CRT_B64="$(vget "$IPREFIX/mongo-ca" tls_crt_b64)"
MONGO_CA_KEY_B64="$(vget "$IPREFIX/mongo-ca" tls_key_b64)"
if [[ -z "$MONGO_CA_CRT_B64" || -z "$MONGO_CA_KEY_B64" ]]; then
  TMPCA="$(mktemp -d)"
  openssl genrsa -out "$TMPCA/ca.key" 4096 2>/dev/null
  openssl req -x509 -new -nodes -key "$TMPCA/ca.key" -sha256 -days 3650 \
    -subj "/CN=${INSTANCE_ID}-mongo-ca" -out "$TMPCA/ca.crt" 2>/dev/null
  MONGO_CA_CRT_B64="$(b64 < "$TMPCA/ca.crt")"
  MONGO_CA_KEY_B64="$(b64 < "$TMPCA/ca.key")"
  rm -rf "$TMPCA"
  echo ">> generated pinned Mongo CA (10y) -> Vault $IPREFIX/mongo-ca"
else
  echo ">> reusing pinned Mongo CA from Vault $IPREFIX/mongo-ca"
fi

ENC="$(printf 'cp:%s' "$IBM_ENTITLEMENT_KEY" | b64)"
DOCKERCFG="$(printf '{"auths":{"cp.icr.io":{"auth":"%s"}}}' "$ENC" | b64)"
vrun "vault kv put $PREFIX/entitlement image_pull_secret_b64='$DOCKERCFG'"
putfile "$MAS_LICENSE_FILE" mas-license.dat
vrun "vault kv put $IPREFIX/license license_id='$MAS_LICENSE_ID' license_file=@/tmp/mas-license.dat; rm -f /tmp/mas-license.dat"
vrun "vault kv put $IPREFIX/manage-crypto cryptoKey='$MANAGE_CRYPTO_KEY' cryptoxKey='$MANAGE_CRYPTOX_KEY'"

if [[ -n "$JDBC_CA_CRT" ]]; then
  putfile "$JDBC_CA_CRT" jdbc-ca.pem
  vrun "vault kv put $IPREFIX/jdbc-system username='$JDBC_USERNAME' password='$JDBC_PASSWORD' jdbc_url='$JDBC_URL' ca.crt=@/tmp/jdbc-ca.pem; rm -f /tmp/jdbc-ca.pem"
else
  vrun "vault kv put $IPREFIX/jdbc-system username='$JDBC_USERNAME' password='$JDBC_PASSWORD' jdbc_url='$JDBC_URL'"
fi

# Pinned Mongo CA: store the keypair (consumed by workloads/mongodb 00-ca.yaml via AVP to build the
# cert-manager ca-issuer) and set ca.crt on mongo + sls-mongo to the SAME CA (consumed by mongocfg/sls).
vrun "vault kv put $IPREFIX/mongo-ca tls_crt_b64='$MONGO_CA_CRT_B64' tls_key_b64='$MONGO_CA_KEY_B64'"
CA_PEM_TMP="$(mktemp)"; printf '%s' "$MONGO_CA_CRT_B64" | base64 -d > "$CA_PEM_TMP"; putfile "$CA_PEM_TMP" mongo-ca.crt; rm -f "$CA_PEM_TMP"

# Dedicated Mongo: write creds + host + the pinned CA (no later harvest needed — the CA is known/fixed).
vrun "vault kv patch $IPREFIX/mongo username='$MONGO_USERNAME' password='$MONGO_PASSWORD' host='$MONGO_HOST' ca.crt=@/tmp/mongo-ca.crt 2>/dev/null || vault kv put $IPREFIX/mongo username='$MONGO_USERNAME' password='$MONGO_PASSWORD' host='$MONGO_HOST' ca.crt=@/tmp/mongo-ca.crt"
vrun "vault kv patch $IPREFIX/sls-mongo username='$SLS_MONGO_USERNAME' password='$SLS_MONGO_PASSWORD' ca.crt=@/tmp/mongo-ca.crt 2>/dev/null || vault kv put $IPREFIX/sls-mongo username='$SLS_MONGO_USERNAME' password='$SLS_MONGO_PASSWORD' ca.crt=@/tmp/mongo-ca.crt"
vrun "rm -f /tmp/mongo-ca.crt"

echo ">> Loaded (generate-once values reused on re-run)."
echo ">> Manage crypto keys: auto-generated/reused from Vault unless ROTATE_MANAGE_CRYPTO_KEYS=true."
echo ">> JDBC: $( [[ -n "$JDBC_CA_CRT" ]] && echo 'TCPS (CA stored)' || echo 'non-SSL (no CA)' )"
echo ">> mongo#host=$MONGO_HOST  (dedicated Mongo; CA is PINNED in Vault $IPREFIX/mongo-ca — no harvest needed)"
echo ">> NEXT: dedicated Mongo uses the pinned CA automatically (sync-mongo-ca.sh is now optional/idempotent)"
echo ">>       after SLS is Ready                 -> scripts/sync-runtime-registration.sh $ENVFILE"
echo ">> Verify: scripts/preflight-vault.sh $ENVFILE"
