apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project }}
  namespace: {{ .Values.argoNamespace }}
spec:
  description: MAS GitOps applications
  sourceRepos: [ "*" ]
  destinations:
    - { server: "*", namespace: "*" }
  clusterResourceWhitelist:
    - { group: "*", kind: "*" }
  namespaceResourceWhitelist:
    - { group: "*", kind: "*" }
