{{- if and .Values.repoSecret .Values.repoSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: repo-platform-gitops
  namespace: {{ .Values.argoNamespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.repoURL }}
  username: {{ .Values.repoSecret.username | quote }}
  password: {{ .Values.repoSecret.password | quote }}
{{- end }}
